In [1]:
# Install libraries from Jupyter Notebook

!pip install numpy

In [1]:
# Lets Import it
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [4]:
np.__config__.show()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <http://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <http://ipython.scipy.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particu

In [6]:
print(np.array.__doc__)

array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is n

# Basic Features of NumPy

In [7]:
# Arange gives you range of values
# Only with end value
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# With start and end value
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
# with start and end value with skip parameter
np.arange(100,9000,2)

array([ 100,  102,  104, ..., 8994, 8996, 8998])

In [10]:
# Linspace is used to create an array with values that are spaced linearly in a specified interval
# By default it creates 50 values
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [11]:
# with specific number of values
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
type(np.linspace(0,10))

numpy.ndarray

# Random Data Generator Example

In [5]:
# Single Random Number
# 0-1
np.random.rand()

0.2939600717769606

In [40]:
# Multiple Random Number
np.random.rand(10)

array([0.13917358, 0.26065845, 0.23257639, 0.28080664, 0.45347559,
       0.80396675, 0.99522327, 0.16020664, 0.61588814, 0.11902834])

In [9]:
# Return a sample (or samples) from the “standard normal” distribution.
np.random.randn()

-0.23167296957825584

In [11]:
# Return a sample (or samples) from the “standard normal” distribution.
# Multiple Numbers
np.mean(np.random.randn(10))

0.44942331917712935

In [13]:
# Single Random Integer Number
np.random.randint(0,10)

2

In [18]:
# Return random integers from low (inclusive) to high (exclusive).
# Random number from range
np.random.randint(10,20)

13

In [27]:
# Return random floats in the half-open interval [0.0, 1.0).
# alias for np.random.rand()
np.random.random_sample()

0.050633052798231604

In [31]:
# Return random floats in the half-open interval [0.0, 1.0).
# multiple values
np.random.random_sample(10)

array([0.8790808 , 0.24127108, 0.31026911, 0.43323421, 0.02826439,
       0.94891407, 0.87198336, 0.81086899, 0.3447671 , 0.78555791])

In [35]:
#Return random floats in the half-open interval [0.0, 1.0]
np.random.random()

0.5209766531458062

In [38]:
#Return random floats in the half-open interval [0.0, 1.0]
np.random.random(10)

array([0.18431075, 0.11703308, 0.45374662, 0.86033736, 0.92145312,
       0.84682792, 0.87989207, 0.75136594, 0.07564838, 0.24040615])

In [46]:
# Generates a random sample from a given 1-D array
np.random.choice(10)

2

In [49]:
# They're just aliases to random_sample:

#import numpy as np

#np.random.random_sample is np.random.random
np.random.random_sample is np.random.rand
#np.random.random_sample is np.random.sample

False

In [51]:
# Draw samples from a uniform distribution.
np.random.uniform()

0.8991525926166749

In [54]:
# Draw samples from a uniform distribution.
np.random.uniform(10)

1.0157046694581275

# Create Array in Python

In [56]:
a = np.array([1,2,3,4])

In [57]:
a

array([1, 2, 3, 4])

In [29]:
type(a)

numpy.ndarray

In [30]:
# shape of array or number of rows & Columns
a.shape

(4,)

In [58]:
# Check dimension of array
a.ndim

1

In [59]:
# Number of elements
a.size

4

In [60]:
a[-1]

4

In [62]:
# higher value is exclusive
a[0:3]

array([1, 2, 3])

In [63]:
# Lets create two dimensional arrays

a = np.array([[1,2,3,4],
              [5,6,7,8]])

In [64]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
type(a)

numpy.ndarray

In [66]:
a.shape

(2, 4)

In [67]:
a.ndim

2

In [68]:
a.size

8

In [70]:
# Get First record
a[0]

array([1, 2, 3, 4])

In [71]:
# Get second record
a[1]

array([5, 6, 7, 8])

In [73]:
# Get first element
#a[0,0]
a[0,0]

1

In [164]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [168]:
arr=arr.reshape(3,3)

In [169]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [180]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [74]:
a[1,1]

6

In [75]:
# Get first row and all columns skipping first
# Slicing of NP array
a[0,1:]

array([2, 3, 4])

In [26]:
# Get all Values
a[:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# Get second row and all columns
a[1,:]

array([5, 6, 7, 8])

In [76]:
# Get second row and columns skipping first
a[::-1]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [77]:
a[0,::-1]

array([4, 3, 2, 1])

# Create Array with alternatives

In [109]:
# Create array with zeros's

a = np.zeros(2,dtype='int')
print(a)
print(a.shape)
print(a.ndim)

# two dimensional array
print()
print("Two dimensional array with Zeros")
a = np.zeros((2,2))
print(a)
print(a.shape)
print(a.ndim)

[0 0]
(2,)
1

Two dimensional array with Zeros
[[0. 0.]
 [0. 0.]]
(2, 2)
2


In [50]:
# Create array with one's

a = np.ones(2)
print(a)
print(a.shape)
print(a.ndim)

# two dimensional array
print()
print("Two dimensional array with Ones")
a = np.ones((3,6))
print(a)
print(a.shape)
print(a.ndim)

[1. 1.]
(2,)
1

Two dimensional array with Ones
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
(3, 6)
2


In [86]:
# Create EMPTY array
# The function empty creates an array whose initial content is random and depends on the state of the memory. 
# The reason to use empty over zeros (or something similar) is speed

np.empty(10)

array([0.13917358, 0.26065845, 0.23257639, 0.28080664, 0.45347559,
       0.80396675, 0.99522327, 0.16020664, 0.61588814, 0.11902834])

In [97]:
np.empty(4)

array([0., 0., 0., 0.])

In [105]:
# Create array with specific value
# One dimension array
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [108]:
# Create two dimensional array with value 20
np.full((5,5),333,dtype='int')

array([[333, 333, 333, 333, 333],
       [333, 333, 333, 333, 333],
       [333, 333, 333, 333, 333],
       [333, 333, 333, 333, 333],
       [333, 333, 333, 333, 333]])

In [111]:
# Create identity matrix
# Digonal will be 1
np.identity(15,dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

# Create array with other data structures

In [112]:
# Create array from list

lst = [1,2,3,4,5,6]
a = np.array(lst)
a
#a.shape

array([1, 2, 3, 4, 5, 6])

In [113]:
# Create array from tuple

st = (1,2,3,4,5,6)
type(st)
np.array(st)

array([1, 2, 3, 4, 5, 6])

# Operations on Array

In [114]:
# Sorting an Array
# 1D array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [115]:
# Sorting an Array
# 2D array
arr = np.array([[2, 1, 5, 3],[7, 4, 6, 8]])
np.sort(arr)

array([[1, 2, 3, 5],
       [4, 6, 7, 8]])

In [116]:
# Finding largest value by index number

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
ind = np.argmax(arr)
print("Index of largest value is :- ", ind)
print("largest value is :- ", arr[ind])

Index of largest value is :-  7
largest value is :-  8


In [117]:
# Finding smallest value by index number

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
ind = np.argmin(arr)
print("Index of smallest value is :- ", ind)
print("smallest value is :- ", arr[ind])

Index of smallest value is :-  1
smallest value is :-  1


In [118]:
# Find out max and min numbers instead of index

data = np.array([2, 1, 5, 3, 7, 4, 6, 8])
data.max()

8

In [119]:
# Find out max and min numbers instead of index

data = np.array([2, 1, 5, 3, 7, 4, 6, 8])
data.min()

1

In [120]:
# Find out total sum of all elements

data = np.array([2, 1, 5, 3, 7, 4, 6, 8])
data.sum()

36

In [121]:
data = np.array([[2, 1, 5, 3],[ 7, 4, 6, 8]])
data

array([[2, 1, 5, 3],
       [7, 4, 6, 8]])

In [123]:
# Row wise mean
np.mean(data,1)

array([2.75, 6.25])

In [124]:
# Column wise mean
np.mean(data,0)

array([4.5, 2.5, 5.5, 5.5])

In [125]:
# Swapping two rows
# Change the index value

data[[1,0]]

array([[7, 4, 6, 8],
       [2, 1, 5, 3]])

In [126]:
# Concatenate two arrays
# 1D array

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
# Concatenation of 2D arrays

a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6], [7, 8]])

# By default it will merge with existing format (on column Level)
c=np.concatenate((a, b))
c
#c.shape

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [137]:
# Concatenation of 2D arrays

a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6], [7, 8]])

# axis 1 addes for rows
c=np.concatenate((a, b),axis=1)


array([[1, 2],
       [3, 4]])

## Reshaping of Array

In [67]:
# Using reshape() will can give a new shape to an array without changing the data. 
# Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements 
# as the original array.

In [138]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [139]:
a.shape

(6,)

In [140]:
# First parameter is number of rows
# Second parameter is number of columns
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [141]:
b = np.random.random(10)
b

array([0.6729667 , 0.73652561, 0.33823136, 0.47129172, 0.59292568,
       0.00551565, 0.23472166, 0.0148275 , 0.91223624, 0.96724479])

In [142]:
b.reshape(5,2)

array([[0.6729667 , 0.73652561],
       [0.33823136, 0.47129172],
       [0.59292568, 0.00551565],
       [0.23472166, 0.0148275 ],
       [0.91223624, 0.96724479]])

In [147]:
# Conditional selection of elements
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [148]:
a.ndim

2

In [149]:
a > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [150]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [151]:
# another way using variable

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [152]:
# Another example

c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [78]:
# Stacking of array

a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])

In [79]:
# In the background it calls for concatenation ONLY
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [80]:
np.concatenate([a1,a2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [81]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# Broadcasting

## There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. 

## This concept is called broadcasting.

In [153]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [154]:
data = np.arange(10,100)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [84]:
data + 100

array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
       123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
       136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
       149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
       162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
       175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187,
       188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199])

In [85]:
data - 100

array([-90, -89, -88, -87, -86, -85, -84, -83, -82, -81, -80, -79, -78,
       -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66, -65,
       -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53, -52,
       -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39,
       -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26,
       -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [86]:
data * 8

array([ 80,  88,  96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176,
       184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280,
       288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384,
       392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488,
       496, 504, 512, 520, 528, 536, 544, 552, 560, 568, 576, 584, 592,
       600, 608, 616, 624, 632, 640, 648, 656, 664, 672, 680, 688, 696,
       704, 712, 720, 728, 736, 744, 752, 760, 768, 776, 784, 792])

# Matrix manipulation in Python

## A matrix is a two-dimensional data structure where numbers are arranged into rows and columns. 

In [156]:
# Two matrices are initialized by value
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

In [157]:
x

array([[1, 2],
       [4, 5]])

In [158]:
y

array([[ 7,  8],
       [ 9, 10]])

In [159]:
print ("Addition of two matrices: ")
print (np.add(x,y))

Addition of two matrices: 
[[ 8 10]
 [13 15]]


In [89]:
print("Subtraction of two matrices : ")
print(np.subtract(x,y))

Subtraction of two matrices : 
[[-6 -6]
 [-5 -5]]


In [72]:
print("Matrix Division : ")
print(np.divide(x,y))

Matrix Division : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [73]:
x

array([[1, 2],
       [4, 5]])

In [74]:
y

array([[ 7,  8],
       [ 9, 10]])

In [70]:
# Numpy multiply or * will do elementwise multiplication

print("Multiplication of two matrices: ")
print(np.multiply(x,y))

Multiplication of two matrices: 
[[ 7 16]
 [36 50]]


In [160]:
# Numpy dot will do vector (pure matrix) multiplication 

print("The product of two matrices : ")
print(np.dot(x,y))

The product of two matrices : 
[[25 28]
 [73 82]]


In [161]:
print("square root is : ")
print(np.sqrt(x))

square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]


In [94]:
print("The summation of elements : ")
print(np.sum(y))

The summation of elements : 
34


In [95]:
print("The column wise summation  : ")
print(y)
print("\n")
print(np.sum(y,axis=0))

The column wise summation  : 
[[ 7  8]
 [ 9 10]]


[16 18]


In [96]:
print("The row wise summation: ")
print(np.sum(y,axis=1))

The row wise summation: 
[15 19]


In [162]:
# using "T" to transpose the matrix
print("Matrix transposition : ")
print("Original X")
print(x)
print("\n")
print(x.T)

Matrix transposition : 
Original X
[[1 2]
 [4 5]]


[[1 4]
 [2 5]]


# Tile Example

## numpy.tile(arr, repetitions) : constructs a new array by repeating array – ‘arr’, the number of times we want to repeat as per repetitions. 

In [163]:
arr = np.arange(5) 
 
repetitions = 2
print("Repeating arr 2 times : \n", np.tile(arr, repetitions)) 
  
repetitions = 3
print("\nRepeating arr 3 times : \n", np.tile(arr, repetitions)) 

Repeating arr 2 times : 
 [0 1 2 3 4 0 1 2 3 4]

Repeating arr 3 times : 
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
